// src/routes/(app)/_app/(checkout)/checkout.tsx
import { useState, useEffect } from "react";
import { useSession } from "@/store/sessionStore";
import { FaMoneyCheckAlt, FaUser } from "react-icons/fa";
import { PiPackageBold } from "react-icons/pi";
import { Calendar } from "lucide-react";
import {
  useNavigate,
  createFileRoute,
  useRouter,
} from "@tanstack/react-router";
import api from "#/lib/api";
import CustomModal, { type Modal } from "@/components/CustomModal";

export const Route = createFileRoute("/(app)/_app/(checkout)/checkout")({
  component: CheckoutPage,
});

export default function CheckoutPage() {
  const navigate = useNavigate();
  const router = useRouter();
  const { usuario } = useSession();

  const location = router.history.location;
  const pacoteState =
    (location.state as any)?.pacote || (window.history.state as any)?.pacote;
  const ofertaState =
    (location.state as any)?.oferta || (window.history.state as any)?.oferta;

  // Estados do Formulário
  const [metodoPagamento, setMetodoPagamento] = useState("cartao-credito");
  const [parcelas, setParcelas] = useState(1);
  const [loading, setLoading] = useState(false);
  const [modal, setModal] = useState<Modal>({
    show: false,
    mensagem: "",
    url: null,
  });

  useEffect(() => {
    if (!pacoteState || !ofertaState) {
      setModal({
        show: true,
        mensagem: "Nenhum pacote ou data selecionados.",
        url: "/buscar",
      });
    }
  }, []);

  if (!pacoteState || !ofertaState) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        {modal.show && <CustomModal modalData={modal} setModal={setModal} />}
      </div>
    );
  }

  // Cálculos
  const valorTotal = ofertaState.preco || 0;
  const descontoPix = valorTotal * 0.05;
  const valorComDescontoPix = valorTotal - descontoPix;

  const formatarValor = (valor: number) => {
    return new Intl.NumberFormat("pt-BR", {
      style: "currency",
      currency: "BRL",
    }).format(valor);
  };

  const handleFinalizarCompra = async () => {
    setLoading(true);

    // Mapeamento para os Enums do Backend
    let metodoEnvio = "VISTA";
    let processadorEnvio = "VISA";

    if (metodoPagamento === "pix") {
      metodoEnvio = "VISTA";
      processadorEnvio = "PIX";
    } else if (metodoPagamento === "cartao-credito") {
      metodoEnvio = parcelas > 1 ? "PARCELADO" : "VISTA";
      processadorEnvio = "MASTERCARD";
    } else if (metodoPagamento === "cartao-debito") {
      metodoEnvio = "VISTA";
      processadorEnvio = "VISA";
    }

    try {
      const response = await api.post("/compra", {
        usuarioId: usuario?.id,
        ofertaId: ofertaState.id,
        metodo: metodoEnvio,
        processador: processadorEnvio,
        parcelas: parcelas,
      });
      const result = response.data;

        navigate({
        to: "/checkout/confirmacao/$compraId",
        params: { compraId: String(result.compra.id) },
      });
    } catch (error: any) {
      console.error(error);
      const msg =
        error.response?.data?.mensagem ||
        "Erro de conexão ao processar compra.";
      setModal({
        show: true,
        mensagem: `Erro na compra: ${msg}`,
        url: null,
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-8">
          <button
            onClick={() => navigate({ to: ".." })}
            className="flex items-center text-gray-600 hover:text-gray-900 mb-4"
          >
            ← Voltar
          </button>
          <h1 className="text-3xl font-bold text-gray-900">Confirmar Compra</h1>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Coluna Esquerda: Dados e Pagamento */}
          <div className="lg:col-span-2 space-y-6">
            {/* Dados do Usuário (Vindo do Store) */}
            <div className="bg-white rounded-lg shadow-md border border-gray-200 p-6">
              <h2 className="text-xl font-semibold text-gray-900 mb-4 flex items-center gap-2">
                <FaUser className="text-xl" />
                Seus Dados
              </h2>
              <div className="space-y-2">
                <p>
                  <strong>Email:</strong> {usuario?.email}
                </p>
              </div>
            </div>

            {/* Forma de Pagamento */}
            <div className="bg-white rounded-lg shadow-md border border-gray-200 p-6">
              <h2 className="text-xl font-semibold text-gray-900 mb-4 flex items-center gap-2">
                <FaMoneyCheckAlt className="text-xl" />
                Forma de Pagamento
              </h2>

              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-3">
                  Selecione como deseja pagar:
                </label>
                <select
                  value={metodoPagamento}
                  onChange={(e) => setMetodoPagamento(e.target.value)}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="cartao-credito">Cartão de Crédito</option>
                  <option value="cartao-debito">Cartão de Débito</option>
                  <option value="pix">PIX</option>
                </select>
              </div>

              {/* Opções Cartão Crédito */}
              {metodoPagamento === "cartao-credito" && (
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Parcelas
                    </label>
                    <select
                      value={parcelas}
                      onChange={(e) => setParcelas(Number(e.target.value))}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg"
                    >
                      {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map((num) => (
                        <option key={num} value={num}>
                          {num}x de {formatarValor(valorTotal / num)}
                          {num > 1 ? " sem juros" : ""}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>
              )}

              {/* Info PIX */}
              {metodoPagamento === "pix" && (
                <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                  <div className="flex items-center">
                    <span className="text-2xl mr-3">🧾</span>
                    <div>
                      <p className="font-semibold text-green-800">
                        5% de desconto no PIX!
                      </p>
                      <p className="text-sm text-green-600">
                        Economize {formatarValor(descontoPix)}
                      </p>
                    </div>
                  </div>
                </div>
              )}
            </div>

            <button
              onClick={handleFinalizarCompra}
              disabled={loading}
              className={`w-full text-white py-4 px-6 rounded-xl font-semibold text-lg shadow-lg transition-all ${
                loading
                  ? "bg-gray-400 cursor-not-allowed"
                  : "bg-green-600 hover:bg-green-700"
              }`}
            >
              {loading
                ? "Processando..."
                : metodoPagamento === "pix"
                  ? `Pagar com PIX - ${formatarValor(valorComDescontoPix)}`
                  : `Confirmar Compra - ${formatarValor(valorTotal)}`}
            </button>
          </div>

          {/* Coluna Direita: Resumo */}
          <div className="space-y-6">
            <div className="bg-white rounded-lg shadow-md border border-gray-200 p-6 sticky top-4">
              <h2 className="text-xl font-semibold text-gray-900 mb-4 flex items-center gap-2">
                <PiPackageBold className="text-3xl" />
                Resumo do Pedido
              </h2>

              <div className="space-y-3 mb-4">
                <div>
                  <span className="text-sm text-gray-500">Pacote</span>
                  <p className="font-medium">{pacoteState.nome}</p>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Localização:</span>
                  <span>
                    {ofertaState.hotel?.cidade?.nome} -{" "}
                    {ofertaState.hotel?.cidade?.estado?.sigla}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Datas</span>
                  <span>
                    <Calendar />
                    {ofertaState.inicio}
                  </span>
                  <span>
                    <Calendar />
                    {ofertaState.fim}
                  </span>
                </div>
              </div>

              <div className="border-t border-gray-200 pt-4">
                <div className="flex justify-between text-sm mb-2">
                  <span>Valor Original:</span>
                  <span>{formatarValor(valorTotal)}</span>
                </div>

                {metodoPagamento === "pix" && (
                  <div className="flex justify-between text-sm text-green-600 mb-2">
                    <span>Desconto PIX:</span>
                    <span>-{formatarValor(descontoPix)}</span>
                  </div>
                )}

                <div className="flex justify-between items-center font-bold text-lg mt-4 pt-4 border-t">
                  <span>Total a pagar:</span>
                  <span className="text-blue-600">
                    {metodoPagamento === "pix"
                      ? formatarValor(valorComDescontoPix)
                      : formatarValor(valorTotal)}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {modal.show && <CustomModal modalData={modal} setModal={setModal} />}
    </div>
  );
}

// src/routes/checkout/+page.svelte
<script lang="ts">
    import GuestLayout from '$lib/layouts/GuestLayout.svelte';
    import { Calendar, CreditCard, Package, User } from 'lucide-svelte';
    import Modal, { type ModalData } from '$lib/components/Modal.svelte';
    import { formatarData, formatarPreco } from '$lib/utils';
    import { apiFetch } from '$lib/api';
    import { auth } from '$lib/auth';
    import { goto } from '$app/navigation';

    let { data } = $props();

    let metodoPagamento = $state('cartao-credito');
    let processing = $state(false);
    let modal = $state<ModalData>({
        show: false,
        mensagem: '',
        url: null,
    });

    let checkoutData = $state({
        oferta_id: data.oferta?.id,
        metodo: 'VISTA',
        processador: 'VISA',
        parcelas: 1,
    });

    const valorTotal = $derived(parseFloat(data.oferta?.price) || 0);
    const descontoPix = $derived(valorTotal * 0.05);
    const valorComDescontoPix = $derived(valorTotal - descontoPix);

    function handleMetodoChange(e: Event) {
        const val = (e.target as HTMLSelectElement).value;
        metodoPagamento = val;
        if (val === 'pix') {
            checkoutData.metodo = 'VISTA';
            checkoutData.processador = 'PIX';
            checkoutData.parcelas = 1;
        } else if (val === 'cartao-credito') {
            checkoutData.metodo = checkoutData.parcelas > 1 ? 'PARCELADO' : 'VISTA';
            checkoutData.processador = 'MASTERCARD';
        } else {
            checkoutData.metodo = 'VISTA';
            checkoutData.processador = 'VISA';
            checkoutData.parcelas = 1;
        }
    }

    function handleParcelasChange(e: Event) {
        const p = Number((e.target as HTMLSelectElement).value);
        checkoutData.parcelas = p;
        checkoutData.metodo = p > 1 ? 'PARCELADO' : 'VISTA';
    }

    async function handleSubmit(e: Event) {
        e.preventDefault();
        processing = true;
        try {
            const response = await apiFetch<any>('/checkout/processar', {
                method: 'POST',
                body: JSON.stringify(checkoutData)
            });
            goto(`/checkout/confirmacao?vendaId=${response.id}`);
        } catch (err: any) {
            modal = {
                show: true,
                mensagem: err.message || 'Erro ao processar compra.',
                url: null,
            };
        } finally {
            processing = false;
        }
    }
</script>

<svelte:head>
    <title>Checkout - PAULA VIAGENS</title>
</svelte:head>

<GuestLayout title="Confirmar Compra">
    <div class="min-h-screen bg-gray-50 py-8">
        <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
            <div class="mb-8">
                <button
                    onclick={() => window.history.back()}
                    class="mb-4 flex cursor-pointer items-center text-gray-600 hover:text-gray-900"
                >
                    ← Voltar
                </button>
                <h1 class="text-3xl font-bold text-gray-900">
                    Confirmar Compra
                </h1>
            </div>

            {#if !data.oferta}
                <div class="rounded-lg border border-gray-200 bg-white p-6 shadow-md text-center">
                    <p class="text-gray-600">Oferta não encontrada ou expirada.</p>
                    <a href="/buscar" class="mt-4 inline-block text-blue-600 hover:underline">Voltar para busca</a>
                </div>
            {:else}
                <form
                    onsubmit={handleSubmit}
                    class="grid grid-cols-1 gap-8 lg:grid-cols-3"
                >
                    <div class="space-y-6 lg:col-span-2">
                        <div class="rounded-lg border border-gray-200 bg-white p-6 shadow-md">
                            <h2 class="mb-4 flex items-center gap-2 text-xl font-semibold text-gray-900">
                                <User size={24} />
                                Seus Dados
                            </h2>
                            <div class="space-y-2">
                                <p>
                                    <strong>Nome:</strong> {$auth.user?.first_name} {$auth.user?.last_name}
                                </p>
                                <p>
                                    <strong>Email:</strong> {$auth.user?.email}
                                </p>
                            </div>
                        </div>

                        <div class="rounded-lg border border-gray-200 bg-white p-6 shadow-md">
                            <h2 class="mb-4 flex items-center gap-2 text-xl font-semibold text-gray-900">
                                <CreditCard size={24} />
                                Forma de Pagamento
                            </h2>

                            <div class="mb-6">
                                <label class="mb-3 block text-sm font-medium text-gray-700">
                                    Selecione como deseja pagar:
                                </label>
                                <select
                                    value={metodoPagamento}
                                    onchange={handleMetodoChange}
                                    class="w-full rounded-lg border border-gray-300 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                                >
                                    <option value="cartao-credito">
                                        Cartão de Crédito
                                    </option>
                                    <option value="cartao-debito">
                                        Cartão de Débito
                                    </option>
                                    <option value="pix">PIX</option>
                                </select>
                            </div>

                            {#if metodoPagamento === 'cartao-credito'}
                                <div class="space-y-4">
                                    <div>
                                        <label class="mb-2 block text-sm font-medium text-gray-700">
                                            Parcelas
                                        </label>
                                        <select
                                            value={checkoutData.parcelas}
                                            onchange={handleParcelasChange}
                                            class="w-full rounded-lg border border-gray-300 px-4 py-3 outline-none"
                                        >
                                            {#each Array.from({ length: 12 }, (_, i) => i + 1) as num}
                                                <option value={num}>
                                                    {num}x de {formatarPreco(valorTotal / num)}
                                                    {num > 1 ? ' sem juros' : ''}
                                                </option>
                                            {/each}
                                        </select>
                                    </div>
                                </div>
                            {/if}

                            {#if metodoPagamento === 'pix'}
                                <div class="rounded-lg border border-green-200 bg-green-50 p-4">
                                    <div class="flex items-center">
                                        <span class="mr-3 text-2xl">🧾</span>
                                        <div>
                                            <p class="font-semibold text-green-800">
                                                5% de desconto no PIX!
                                            </p>
                                            <p class="text-sm text-green-600">
                                                Economize {formatarPreco(descontoPix)}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {/if}
                        </div>

                        <button
                            type="submit"
                            disabled={processing}
                            class="w-full rounded-xl px-6 py-4 text-lg font-semibold text-white shadow-lg transition-all {processing ? 'cursor-not-allowed bg-gray-400' : 'cursor-pointer bg-green-600 hover:bg-green-700'}"
                        >
                            {processing
                                ? 'Processando...'
                                : metodoPagamento === 'pix'
                                    ? `Pagar com PIX - ${formatarPreco(valorComDescontoPix)}`
                                    : `Confirmar Compra - ${formatarPreco(valorTotal)}`}
                        </button>
                    </div>

                    <div class="space-y-6">
                        <div class="sticky top-4 rounded-lg border border-gray-200 bg-white p-6 shadow-md">
                            <h2 class="mb-4 flex items-center gap-2 text-xl font-semibold text-gray-900">
                                <Package size={30} class="text-blue-600" />
                                Resumo
                            </h2>

                            <div class="mb-4 space-y-3">
                                <div>
                                    <span class="text-sm font-bold tracking-tight text-gray-500 uppercase">
                                        Pacote
                                    </span>
                                    <p class="font-medium">
                                        {data.oferta.package?.name}
                                    </p>
                                </div>
                                <div class="flex justify-between text-sm">
                                    <span class="text-gray-600">
                                        Localização:
                                    </span>
                                    <span class="font-medium text-right">
                                        {data.oferta.hotel?.cidade?.name} - {data.oferta.hotel?.cidade?.estado?.code}
                                    </span>
                                </div>
                                <div class="space-y-1">
                                    <div class="flex items-center gap-2 text-sm text-gray-600">
                                        <Calendar size={14} />
                                        <span>
                                            Embarque: {formatarData(data.oferta.start_date)}
                                        </span>
                                    </div>
                                    <div class="flex items-center gap-2 text-sm text-gray-600">
                                        <Calendar size={14} />
                                        <span>
                                            Retorno: {formatarData(data.oferta.end_date)}
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="border-t border-gray-200 pt-4">
                                <div class="mb-2 flex justify-between text-sm">
                                    <span>Valor Original:</span>
                                    <span>{formatarPreco(valorTotal)}</span>
                                </div>

                                {#if metodoPagamento === 'pix'}
                                    <div class="mb-2 flex justify-between text-sm text-green-600">
                                        <span>Desconto PIX:</span>
                                        <span>-{formatarPreco(descontoPix)}</span>
                                    </div>
                                {/if}

                                <div class="mt-4 flex items-center justify-between border-t pt-4 text-lg font-bold">
                                    <span>Total:</span>
                                    <span class="text-blue-600">
                                        {metodoPagamento === 'pix'
                                            ? formatarPreco(valorComDescontoPix)
                                            : formatarPreco(valorTotal)}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            {/if}
        </div>
    </div>
    <Modal modalData={modal} onClose={() => (modal.show = false)} />
</GuestLayout>
