// src/components/administracao/SideBar.tsx
import { useState } from "react";
import logo from "/iconcor.png";
import { BiSolidPieChartAlt2 } from "react-icons/bi";
import { IoIosArrowDropupCircle } from "react-icons/io";
import { FaUserCog } from "react-icons/fa";
import { FaMapMarkedAlt } from "react-icons/fa";
import { HiMiniCamera } from "react-icons/hi2";
import { FaHotel } from "react-icons/fa6";
import { FaTruckPlane } from "react-icons/fa6";
import { useLocation, useNavigate } from "@tanstack/react-router";
import { ROUTES } from "#/utils/paths";

export default function Sidebar() {
  const navigate = useNavigate();
  const location = useLocation();

  const [isAdminOpen, setIsAdminOpen] = useState(true);

  const isActive = (path: string) => location.pathname === path;

  const linkClass = (path: string, isSubItem = false) => `
    w-full text-left px-4 py-2 rounded-lg font-medium transition-colors mb-1
    ${isSubItem ? "text-sm pl-8" : ""}
    ${
      isActive(path)
        ? "bg-blue-50 text-blue-600 border border-blue-200"
        : "text-gray-700 hover:bg-gray-100"
    }
  `;

  return (
    <div className="w-64 bg-white shadow-lg shrink-0 flex flex-col h-full sticky top-0" style={{ maxHeight: "calc(100vh - 80px)" }}>
      <div className="p-6 border-b border-gray-200">
        <div className="flex justify-center md:w-2.1">
          <img
            src={logo}
            alt="Equipe de atendimento"
            onClick={() => navigate({ to: "/" })}
            className="max-w-37.5 rounded-xl shadow-lg object-contain p-2 cursor-pointer"
          />
        </div>
      </div>

      <nav className="p-4 flex-1 overflow-y-auto">
        <div className="space-y-1">
          <button
            onClick={() => navigate({ to: "/administracao/dashboard" })}
            className={linkClass("/dashboard")}
          >
            <div className="pl-4 flex items-center">
              <BiSolidPieChartAlt2 className="text-lgg mr-2 pb-0.5" />
              Dashboard
            </div>
          </button>

          <div>
            <button
              onClick={() => setIsAdminOpen(!isAdminOpen)}
              className="w-full text-left px-4 py-2 rounded-lg font-bold text-gray-800 hover:bg-gray-50 flex justify-between items-center"
            >
              <span>OPÇÕES</span>
              <span
                className={`transform transition-transform ${
                  isAdminOpen ? "rotate-180" : ""
                }`}
              >
                <IoIosArrowDropupCircle className="text-lgg mr-2 pb-0.5" />
              </span>
            </button>

            {isAdminOpen && (
              <div className="mt-1 space-y-1">
                <button
                  onClick={() =>
                    navigate({ to: "/administracao/pacote/listar" })
                  }
                  className={linkClass("/pacote/listar", true)}
                >
                  <div className="flex items-center">
                    <FaMapMarkedAlt className="text-lg mr-2 pb-0.5" />
                    Pacotes de Viagem
                  </div>
                </button>
                <button
                  onClick={() =>
                    navigate({ to: "/administracao/pacotedefoto/listar" })
                  }
                  className={linkClass(ROUTES.PACOTES_FOTO_LISTA, true)}
                >
                  <div className="flex items-center">
                    <HiMiniCamera className="text-lg mr-2 pb-0.5" />
                    Pacotes de Fotos
                  </div>
                </button>

                <button
                  onClick={() =>
                    navigate({ to: "/administracao/hotel/listar" })
                  }
                  className={linkClass(ROUTES.HOTEIS_LISTA, true)}
                >
                  <div className="flex items-center">
                    <FaHotel className="text-lg mr-2 pb-0.5" />
                    Hotéis
                  </div>
                </button>

                <button
                  onClick={() =>
                    navigate({ to: "/administracao/transporte/listar" })
                  }
                  className={linkClass(ROUTES.TRANSPORTES_LISTA, true)}
                >
                  <div className="flex items-center">
                    <FaTruckPlane className="text-lg mr-2 pb-0.5" />
                    Transporte
                  </div>
                </button>
                <button
                  onClick={() =>
                    navigate({ to: "/administracao/usuario/listar" })
                  }
                  className={linkClass(ROUTES.LISTAR_USUARIOS, true)}
                >
                  <div className="flex items-center">
                    <FaUserCog className="text-lg mr-2 pb-0.5" />
                    Usuários
                  </div>
                </button>
              </div>
            )}
          </div>
        </div>
      </nav>

      <div className="p-4 border-t text-xs text-gray-400 text-center">
        Versão 1.0.0
      </div>
    </div>
  );
}

// src/lib/components/administracao/SideBar.svelte
<script lang="ts">
    import { page } from '$app/state';
    import {
        LayoutDashboard,
        MapPinned,
        Camera,
        Hotel,
        Truck,
        Users,
        ChevronDown,
        Tag,
    } from 'lucide-svelte';
    import Image from '../Image.svelte';

    let isAdminOpen = $state(true);

    const isActive = (path: string) => {
        const url = page.url.pathname;
        if (path === '/admin/dashboard') {
            return url === path;
        }
        return url === path || url.startsWith(`${path}/`);
    };

    const linkClass = (path: string, isSubItem = false) => {
        const active = isActive(path);
        return `
            flex items-center gap-3 px-4 py-2 rounded-lg font-medium transition-colors mb-1
            ${isSubItem ? 'text-sm pl-8' : ''}
            ${
                active
                    ? 'bg-blue-50 text-blue-600 border border-blue-200'
                    : 'text-gray-700 hover:bg-gray-100'
            }
        `;
    };
</script>

<aside class="sticky top-0 flex h-screen w-64 shrink-0 flex-col bg-white shadow-lg">
    <div class="flex justify-center border-b border-gray-200 p-6">
        <a href="/">
            <Image
                name="logo_cor"
                alt="Paula viagens logo"
                style="max-h-full max-w-full rounded-xl object-contain p-2"
            />
        </a>
    </div>

    <nav class="flex-1 overflow-y-auto p-4">
        <div class="space-y-1">
            <a
                href="/admin/dashboard"
                class={linkClass('/admin/dashboard')}
            >
                <LayoutDashboard size={20} />
                <span>Dashboard</span>
            </a>

            <div>
                <button
                    onclick={() => (isAdminOpen = !isAdminOpen)}
                    class="flex w-full items-center justify-between rounded-lg px-4 py-2 font-bold text-gray-800 hover:bg-gray-50"
                >
                    <span class="text-xs tracking-wider uppercase">
                        Opções
                    </span>
                    <ChevronDown
                        size={16}
                        class="transform transition-transform {isAdminOpen ? 'rotate-180' : ''}"
                    />
                </button>

                {#if isAdminOpen}
                    <div class="mt-1 space-y-1">
                        <a
                            href="/admin/pacote"
                            class={linkClass('/admin/pacote', true)}
                        >
                            <MapPinned size={18} />
                            <span>Pacotes de Viagem</span>
                        </a>
                        <a
                            href="/admin/pacotedefoto"
                            class={linkClass('/admin/pacotedefoto', true)}
                        >
                            <Camera size={18} />
                            <span>Pacotes de Fotos</span>
                        </a>

                        <a
                            href="/admin/hotel"
                            class={linkClass('/admin/hotel', true)}
                        >
                            <Hotel size={18} />
                            <span>Hotéis</span>
                        </a>

                        <a
                            href="/admin/transporte"
                            class={linkClass('/admin/transporte', true)}
                        >
                            <Truck size={18} />
                            <span>Transporte</span>
                        </a>
                        <a
                            href="/admin/oferta"
                            class={linkClass('/admin/oferta', true)}
                        >
                            <Tag size={18} />
                            <span>Ofertas</span>
                        </a>
                        <a
                            href="/admin/usuario"
                            class={linkClass('/admin/usuario', true)}
                        >
                            <Users size={18} />
                            <span>Usuários</span>
                        </a>
                    </div>
                {/if}
            </div>
        </div>
    </nav>

    <div class="border-t p-4 text-center text-xs text-gray-400">
        Versão 2.0.0
    </div>
</aside>
